#!/bin/bash -x

# called if new metadata is available
# metadata can be accessed from environment variables

# echo New Track Info:
# echo Title:  $TITLE
# echo Artist: $ARTIST
# echo Album: $ALBUM
# echo Genre: $GENRE
# echo